### ISSUE TITLE
Pug failides kood korda!

### ISSUE THREAD

**Issue by argoroots** [poff-bnff/tartuff#44]
- [x] Otsustage kas kasutate " või ' ja muutke kood. Soovitav on '.

- [x] Süntaks kujule _tag#id.class(attr)_. Hetle osades kohtades segamini järjekord.

- [x] Tagi atribuudid eraldada komaga. Või mitte. Aga ühtemoodi igalpool.

- [x] Muutuja omistamisel kasutad _var_'i.

- [x] Tagi üherealine sisu ühele reale:
  ```
  .str_info_meta_label
       | Festival
  ```
  asemel
  ```
  .str_info_meta_label Festival
  ```

- [x] Mitmeosalised stringide liitmised ES6 template kujule:
  ```
  '/assets/img/img_articles/' + my_path + '/' + articlePic.heroImage
  ```
  asemel
  ```
  `/assets/img/img_articles/${my_path}/${articlePic.heroImage}`
  ```

- [x] _extends_ ja _include_ juures kasutada _source_ kaustale viitamisel /. Hetkel segamini / ja relative path (..).

- [x] head.pug on HTML ja Pug süntaks segamini.

- [x] footer.pug'is olev inline JS viia välisesse JSi (_scripts kaustas).

**Comment by jaanleppik** [comment]
Aitäh! Võtame esmaspäeval kohe ette, ongi refaktoorimise päev plaanis.

**Comment by marianntapfer** [comment]
Ma ei saa sellest päris täpselt aru neljandast punktist: Muutuja omistamisel kasutad var'i. -  Pug failides on muutuja omistamisel kasutatud var. Javascriptis on kasutatud let. Kas nii pole õige? Kuidas hea stiil ette näeb? Mida peaks peaksin siin muutma?

**Comment by argoroots** [comment]
> Ma ei saa sellest päris täpselt aru neljandast punktist: Muutuja omistamisel kasutad var'i. - Pug failides on muutuja omistamisel kasutatud var. Javascriptis on kasutatud let. Kas nii pole õige? Kuidas hea stiil ette näeb? Mida peaks peaksin siin muutma?

näiteks:
https://github.com/poff-bnff/tartuff/blob/8d0841bb6a3e4065758d36c765a25a7e33f12045/source/article/index.pug#L11

võiks olla:
`- var articlePics = self.data.article_pictures.articles`

**Comment by mitselek** [comment]
Õpetussõnad viidud wikisse
