### ISSUE TITLE
Yaml failid korda

### ISSUE THREAD

**Issue by argoroots** [poff-bnff/tartuff#46]
Näited ühele failile, aga vaadata ka muud üle.

- [x] Ilma ' ja algusesse pole vaja /.
  https://github.com/poff-bnff/tartuff/blob/8d0841bb6a3e4065758d36c765a25a7e33f12045/source/articles/data.yaml#L1

- [x] Source kataloog on /. Võiks mitte kasutada relative pathe.
  https://github.com/poff-bnff/tartuff/blob/8d0841bb6a3e4065758d36c765a25a7e33f12045/source/articles/data.yaml#L3

- [x] Mis see on? Mitmerealise väärtuse jaoks on |.
  https://github.com/poff-bnff/tartuff/blob/8d0841bb6a3e4065758d36c765a25a7e33f12045/source/film/data.yaml#L101

- [x] Alias on Array. Pealegi home path on ''.
  https://github.com/poff-bnff/tartuff/blob/8d0841bb6a3e4065758d36c765a25a7e33f12045/source/films/data.yaml#L2

**Comment by mitselek** [comment]
õpetussõnad kopitud wikisse
