### ISSUE TITLE
Datetime väärtuse formaat frontendis

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/tartuff#9]
Praegu tuleb datetime väärtus, näiteks artikli juures, mitte eriti inimloetavalt. 
Seda peaks aga näitama vastavalt kasutaja locale'le: 
eestis 22.11.2020 19:00
USAs  11.22.2020 19:00
jne

**Comment by mitselek** [comment]
proovime https://momentjs.com

**Comment by argoroots** [comment]
Miks kliendi poole Moment JS kui saab kuupäeva templeidi sees vanilla JS kasutades õige _locale_ panna?!
